spring:
  application:
    name: catalog
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog # si no usamos docker que mapee a localhost, sino vien del .env con catalog-db para red interna
    username: root
    password: root

  server:
    port: 8080

  grpc:
    server:
      port: 9090
      enable-keep-alive: true

catalog:
  policy:
    draft-ttl: P2D